config/routes.rb
Rails.application.routes.draw do

  return if defined? Rails::Generators

  devise_scope :user do
      authenticated do
        resources :authors
        resources :articles
        root "articles#index"
      end
    end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true
    belongs_to :author
    # validates (:title, presence: true, length: { minimum: 5 })
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :articles

    def full_name
        "#{first_name} #{last_name}"
    end
end

app/models/user.rb
class User < UserBase

  def self.with_credentials(auth)
    # Override this method to handle the lookup/creation of a user from an omniauth response
    super
  end
end

app/controllers/application_controller.rb
require "strongmind/exceptions"

class ApplicationController < ActionController::Base
  include StrongMindNav
  before_action :authenticate_user!
  before_action :fetch_common_nav

  # Implement the list of menu items for the application
  # def menu_items
  #   [
  #     { name: 'Home', icon: 'fa-solid fa-house', url: root_path }
  #   ]
  # end

  include StrongMindNav
  before_action :authenticate_user!
  before_action :fetch_common_nav

  # Implement the list of menu items for the application
  def menu_items
    [
      { name: 'Home', icon: 'fa-solid fa-house', url: articles_path }
    ]
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy!

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :body, :author_id)
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy ]

  # GET /authors or /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1 or /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors or /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to author_url(@author), notice: "Author was successfully created." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to author_url(@author), notice: "Author was successfully updated." }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    @author.destroy!

    respond_to do |format|
      format.html { redirect_to authors_url, notice: "Author was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>" class="flex flex-col gap-5 p-10 min-w-[480px] border rounded transition-all flex-1 hover:border-neutral-800 hover:shadow">

  <div class="flex flex-col gap-2.5">
    <h1><%= article.title %></h1>
    
    <p>
      by <strong><%= article.author.full_name %></strong> on <em><%= article.created_at.strftime("%B %d, %Y") %></em>
    </p>
  </div>

  <div class="flex flex-1">
    <p>
      <%= truncate(article.body, length: 150) %>
    </p>
  </div>

  <hr />

  <div class="flex justify-center">
    <%= link_to article, class: "sm-btn sm-btn-tertiary" do %>
      <i class="fa-light fa-newspaper"></i> View Article
    <% end %>
  </div>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article, class: "flex flex-col gap-5") do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset class="flex flex-col flex-1 gap-1">
    <%= form.label :title %>

    <div class="sm-input-container">
      <%= form.text_field :title %>
    </div>
  </fieldset>

  <fieldset class="flex flex-col flex-1 gap-1">
    <%= form.label :body %>

    <div class="sm-input-container">
      <%= form.text_area :body %>
    </div>
  </fieldset>

  <fieldset class="flex flex-col flex-1 gap-1">
    <%= form.label :author %>

    <div class="sm-input-container">
      <%= form.collection_select :author_id, Author.all, :id, :full_name, prompt: "Select an Author" %>
    </div>
  </fieldset>

  <hr />

  <div class="flex">
    <%= form.submit class: "sm-btn sm-btn-primary" do %>
      Hello
    <% end %>
  </div>
<% end %>

app/views/articles/_show_article.html.erb
<div id="<%= dom_id article %>" class="flex flex-col gap-5">
  <div class="flex flex-col gap-2.5">
    <h1>
      <%= article.title %>
    </h1>

    <p>
      By <strong><%= article.author.full_name %></strong> on <em><%= article.created_at.strftime("%B %d, %Y") %></em>
    </p>
  </div>

  <p>
    <%= article.body %>
  </p>
</div>

app/views/articles/edit.html.erb
<header class="flex gap-5 justify-between items-center">
  <%= link_to articles_path, class: "sm-btn sm-btn-link" do %>
    <i class="fa-light fa-chevron-left"></i> Back to Articles  
  <% end %>

  <%= link_to "Show this article", @article, class: "sm-btn sm-btn-outline" %>
</header>

<h1>Editing Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<% if notice.present? %>
  <div class="sm-alert sm-alert-success">
    <div class="flex items-center justify-between gap-5">
      <div class="icon-container">
        <i class="fa-solid fa-check text-xl"></i>
      </div>
      <p class="flex-1"><%= notice %></p>
    </div>
  </div>
<% end %>

<header class="flex justify-center">
  <div class="flex flex-1 justify-center pl-[147px]">
    <h1>List of Articles</h1>
  </div>

  <%= link_to new_article_path, class: "sm-btn sm-btn-outline" do %>
    <i class="fa-light fa-pen-nib"></i> Write an Article
  <% end %>
</header>

<hr />

<div id="articles" class="flex flex-wrap gap-5">
  <% @articles.each do |article| %>
    <%= render article %>
  <% end %>
</div>

app/views/articles/new.html.erb
<header class="flex gap-5">
  <%= link_to articles_path, class: "sm-btn sm-btn-link" do %>
    <i class="fa-light fa-chevron-left"></i> Back to Articles  
  <% end %>
</header>

<h1>Write an Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<% if notice.present? %>
  <div class="sm-alert sm-alert-success">
    <div class="flex items-center justify-between gap-5">
      <div class="icon-container">
        <i class="fa-solid fa-check text-xl"></i>
      </div>
      <p class="flex-1"><%= notice %></p>
    </div>
  </div>
<% end %>

<header class="flex gap-5">
  <%= link_to articles_path, class: "sm-btn sm-btn-link" do %>
    <i class="fa-light fa-chevron-left"></i> Back to Articles  
  <% end %>
</header>

<%= render "show_article", article: @article %>

<hr />

<div class="flex justify-center gap-2.5">
  <%= button_to @article, method: :delete, class: "sm-btn sm-btn-delete" do %>
    <i class="fa-light fa-trash-can"></i> Delete
  <% end %>

  <%= link_to edit_article_path(@article), class: "sm-btn sm-btn-tertiary" do %>
    <i class="fa-light fa-edit"></i> Edit this Article
  <% end %>  
</div>

app/views/authors/_author.html.erb
<div id="<%= dom_id author %>">
  <h1>
    <%= author.first_name %> <%= author.last_name %>
  </h1>
</div>

app/views/authors/_form.html.erb
<%= form_with(model: author, class: "flex flex-col gap-5") do |form| %>
  <% if author.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset class="flex flex-col flex-1 gap-1">
    <%= form.label :first_name %>

    <div class="sm-input-container">
      <%= form.text_field :first_name %>
    </div>
  </fieldset>

  <fieldset class="flex flex-col flex-1 gap-1">
    <%= form.label :last_name %>

    <div class="sm-input-container">
      <%= form.text_field :last_name %>
    </div>
  </fieldset>

  <hr />

  <div class="flex">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<header class="flex gap-5 justify-between items-center">
  <%= link_to authors_path, class: "sm-btn sm-btn-link" do %>
    <i class="fa-light fa-chevron-left"></i> Back to authors
  <% end %>

  <%= link_to "Show this author", @author, class: "sm-btn sm-btn-outline" %>
</header>

<h1>Editing Author</h1>

<%= render "form", author: @author %>

app/views/authors/index.html.erb
<% if notice.present? %>
  <div class="sm-alert sm-alert-success">
    <div class="flex items-center justify-between gap-5">
      <div class="icon-container">
        <i class="fa-solid fa-check text-xl"></i>
      </div>
      <p class="flex-1"><%= notice %></p>
    </div>
  </div>
<% end %>

<header class="flex justify-center">
  <div class="flex flex-1 justify-center pl-[185px]">
    <h1>Authors</h1>
  </div>

  <%= link_to new_author_path, class: "sm-btn sm-btn-outline" do %>
    <i class="fa-light fa-address-card"></i> Create a New Author
  <% end %>
</header>

<hr />

<div id="authors" class="flex flex-wrap gap-5">
  <% @authors.each do |author| %>
    <div class="flex flex-col gap-5 p-10 border rounded min-w-[320px] transition-all flex-1 hover:border-neutral-800 hover:shadow">
      <%= render author %>

      <div class="flex">
        <%= link_to author, class: "sm-btn sm-btn-tertiary" do %>
          <i class="fa-light fa-address-card"></i> View Author
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/authors/new.html.erb
<header class="flex gap-5">
  <%= link_to authors_path, class: "sm-btn sm-btn-link" do %>
    <i class="fa-light fa-chevron-left"></i> Back to authors
  <% end %>
</header>

<h1>Create a New Author</h1>

<%= render "form", author: @author %>

app/views/authors/show.html.erb
<% if notice.present? %>
  <div class="sm-alert sm-alert-success">
    <div class="flex items-center justify-between gap-5">
      <div class="icon-container">
        <i class="fa-solid fa-check text-xl"></i>
      </div>
      <p class="flex-1"><%= notice %></p>
    </div>
  </div>
<% end %>

<header class="flex gap-5">
  <%= link_to authors_path, class: "sm-btn sm-btn-link" do %>
    <i class="fa-light fa-chevron-left"></i> Back to authors  
  <% end %>
</header>

<%= render @author %>

<div class="flex gap-5">
  <%= button_to @author, method: :delete, class: "sm-btn sm-btn-delete" do %>
    <i class="fa-light fa-trash-can"></i> Delete Author
  <% end %>

  <%= link_to edit_author_path(@author), class: "sm-btn sm-btn-outline" do %>
    <i class="fa-light fa-edit"></i> Edit Author
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'https://cdn.strongmind.com/backpack-ui/latest/assets/css/BackpackUI.css' %>
    <%== @theme_css %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="strongmind-ui">
    <%== @top_navbar_html %>  
    <main class="flex flex-col gap-5 p-10 mx-auto">
      <%= yield %>
    </main>
    <%== @bottom_navbar_html %>  
  </body>
</html>